#
dangerous-blocks:
  water:
    - "minecraft:water"
    - "minecraft:bubble_column"
  fire:
    - "minecraft:fire"
    - "minecraft:soul_fire"
    - "minecraft:magma_block"
    - "minecraft:lava"
  earth:
    - "minecraft:cactus"
    - "minecraft:sweet_berry_bush"
  air:
    - "minecraft:air"
    - "minecraft:void_air"
    - "minecraft:cave_air"