#
blacklisted-blocks:
  - "minecraft:cactus"
  - "minecraft:sweet_berry_bush"
  - "minecraft:powder_snow"
# whether the safety checks should be bypassed when players are in these states - a bypass permission can also be granted
safety-bypass:
  creative: true
  invulnerable: true