name: SimpleHomes
version: '${project.version}'
main: simplexity.simplehomes.SimpleHomes
api-version: '1.20'
commands:
  sethome:
    permission: homes.sethome
    description: Sets a home
  delhome:
    permission: homes.delhome
    description: Deletes a home
  home:
    permission: homes.teleport
    description: Teleports to a home
permissions:
  homes:
    default: op
    description: allows base plugin functionality
  homes.sethome:
    default: op
    description: allows player to set home
  homes.delhome:
    default: op
    description: allows player to delete home
  homes.teleport:
    default: op
    description: allows player to teleport to home
  homes.count:
    default: op
    description: base for permission on number of homes you can have
  homes.count.bypass:
    default: op
    description: allows for setting infinite homes regardless of how many you have set as the max
