name: SimpleHomes
version: '${project.version}'
main: simplexity.simplehomes.SimpleHomes
api-version: '1.20'
author: RhythmicSys
description: A basic plugin for setting and teleporting to locations
commands:
  sethome:
    permission: homes.commands.sethome
    description: Sets a home
  delhome:
    permission: homes.commands.delhome
    description: Deletes a home
  home:
    permission: homes.commands.home
    description: Teleports to a home
  homesreload:
    permission: homes.reload
    description: reloads the config
  homelist:
    permission: homes.commands.list
    description: lists your homes
  importhomes:
    permission: homes.import
    description: Console only command for importing from other plugins.
permissions:
  homes:
    default: true
    description: allows base plugin functionality
  homes.commands:
    default: true
    description: allows player to use commands
    children:
      homes.commands.sethome: true
      homes.commands.delhome: true
      homes.commands.home: true
      homes.commands.list: true
      homes.bed: true
  homes.bed:
    default: true
    description: sets a home at your bed when you interact with it
  homes.commands.sethome:
    default: true
    description: allows player to set home
  homes.commands.delhome:
    default: true
    description: allows player to delete home
  homes.commands.home:
    default: true
    description: allows player to teleport to home
  homes.commands.list:
    default: true
    description: allows you to list your own homes
  homes.count:
    default: op
    description: base for permission on number of homes you can have
  homes.count.bypass:
    default: op
    description: allows for setting infinite homes regardless of how many you have set as the max
  homes.safety.bypass:
    default: false
    description: allows bypassing the safety checks
  homes.delay.bypass:
    default: op
    description: bypasses the delay for teleportation to homes
  homes.import:
    default: op
    description: this permission does nothing outside of prevent this command from being shown to players, granting the permission to someone will still not allow them to run the command
  homes.reload:
    default: op
    description: allows reloading the config
  homes.admin.teleport:
    default: op
    description: allows teleporting to other players' homes with the -p argument